#!/usr/bin/env bash
# Rebuild Resources/katex-inlined.min.css from an unpacked KaTeX npm package.
#
# Why this exists: the math renderer loads its HTML with `baseURL: nil` (like the mermaid one), so a
# relative `@font-face { src: url(fonts/KaTeX_Main-Regular.woff2) }` resolves against nothing and every
# glyph silently falls back to a system font — the classic embedded-WebView trap. Inlining the fonts as
# data: URIs removes the resolution step entirely, and keeps the render hermetic: no baseURL, no file
# reads, no network, identical output on every Mac.
#
# Run only when bumping the KaTeX version:
#   npm pack katex@<version> && tar xf katex-<version>.tgz
#   ./Scripts/build-katex-css.sh <path-to-unpacked>/package
set -euo pipefail

PKG="${1:?usage: build-katex-css.sh <unpacked katex package dir>}"
SRC="$PKG/dist/katex.min.css"
FONTS="$PKG/dist/fonts"
OUT="$(cd "$(dirname "$0")/.." && pwd)/Resources/katex-inlined.min.css"

[ -f "$SRC" ] || { echo "no katex.min.css at $SRC" >&2; exit 1; }
VERSION="$(node -p "require('$PKG/package.json').version")"

# Keep only woff2 sources: WebKit supports it everywhere we run, and dropping the ttf/woff fallbacks
# (which the CSS lists for older browsers) cuts the payload by ~3x for identical output.
python3 - "$SRC" "$FONTS" "$OUT" "$VERSION" <<'PY'
import base64, os, re, sys

src, fonts, out, version = sys.argv[1:5]
css = open(src, encoding="utf-8").read()

cache = {}
def data_uri(name):
    if name not in cache:
        with open(os.path.join(fonts, name), "rb") as f:
            cache[name] = "data:font/woff2;base64," + base64.b64encode(f.read()).decode()
    return cache[name]

missing = []
def replace(m):
    # One src: list per @font-face — rewrite it down to the single inlined woff2.
    woff2 = re.search(r"url\(fonts/([^)]+\.woff2)\)", m.group(0))
    if not woff2:
        return m.group(0)
    name = woff2.group(1)
    if not os.path.exists(os.path.join(fonts, name)):
        missing.append(name)
        return m.group(0)
    return "src:url(%s) format(\"woff2\")" % data_uri(name)

css_out = re.sub(r"src:[^;}]*?\.woff2\)[^;}]*", replace, css)

if missing:
    sys.exit("font files missing from the package: %s" % ", ".join(missing))
# Nothing may still point at a relative path — that would silently fall back at render time.
leftover = re.findall(r"url\((?!data:)[^)]*\)", css_out)
if leftover:
    sys.exit("unresolved relative url() left in CSS: %s" % leftover[:3])

header = "/* KaTeX %s CSS with its fonts inlined as data: URIs. Generated by Scripts/build-katex-css.sh — do not edit by hand. See THIRD-PARTY-NOTICES.md. */\n" % version
open(out, "w", encoding="utf-8").write(header + css_out)
print("wrote %s (%.0f KB, %d fonts inlined)" % (out, os.path.getsize(out) / 1024, len(cache)))
PY
